//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinaPAS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autos()
        {
            this.Bienes = new HashSet<Bienes>();
        }
    
        public int Id { get; set; }
        public string Dominio { get; set; }
        public string MarcaModelo { get; set; }
        public Nullable<int> Anio { get; set; }
        public string Chasis { get; set; }
        public string Motor { get; set; }
        public string Tipo { get; set; }
        public string Uso { get; set; }
        public string GNC { get; set; }
        public string Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bienes> Bienes { get; set; }
    }
}
