//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinaPAS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bienes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bienes()
        {
            this.Endosos = new HashSet<Endosos>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Item { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string Ubicacion { get; set; }
        public string Ciudad { get; set; }
        public string Provincia { get; set; }
        public string Acreedor { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public int idAuto { get; set; }
    
        public virtual Autos Autos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endosos> Endosos { get; set; }
    }
}
