//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinaPAS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cajas()
        {
            this.Movimientos_Caja = new HashSet<Movimientos_Caja>();
        }
    
        public int Id_Caja { get; set; }
        public Nullable<System.DateTime> Fecha_Apertura { get; set; }
        public Nullable<System.DateTime> Fecha_Cierre { get; set; }
        public Nullable<decimal> Monto_Inicial { get; set; }
        public Nullable<decimal> Monto_Final { get; set; }
        public string Estado { get; set; }
        public int idusuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimientos_Caja> Movimientos_Caja { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
