//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinaPAS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuotas()
        {
            this.Recibos = new HashSet<Recibos>();
        }
    
        public int id { get; set; }
        public int numero { get; set; }
        public System.DateTime vencimiento { get; set; }
        public System.DateTime convenio { get; set; }
        public decimal valor { get; set; }
        public bool pagada { get; set; }
        public int idendoso { get; set; }
    
        public virtual Endosos Endosos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recibos> Recibos { get; set; }
    }
}
