//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinaPAS_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MartinaPASEntities : DbContext
    {
        public MartinaPASEntities()
            : base("name=MartinaPASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autos> Autos { get; set; }
        public virtual DbSet<Bienes> Bienes { get; set; }
        public virtual DbSet<Cajas> Cajas { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Cuotas> Cuotas { get; set; }
        public virtual DbSet<Endosos> Endosos { get; set; }
        public virtual DbSet<Movimientos_Caja> Movimientos_Caja { get; set; }
        public virtual DbSet<Polizas> Polizas { get; set; }
        public virtual DbSet<Privilegios> Privilegios { get; set; }
        public virtual DbSet<Recibos> Recibos { get; set; }
        public virtual DbSet<Rol_Privilegio> Rol_Privilegio { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoMovCaja> TipoMovCaja { get; set; }
        public virtual DbSet<Usuario_Rol> Usuario_Rol { get; set; }
        public virtual DbSet<Sesiones> Sesiones { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
