//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinaPAS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Privilegio
    {
        public int Id_Rol_Privilegio { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public Nullable<int> Id_Privilegio { get; set; }
    
        public virtual Privilegios Privilegios { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
