//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartinaPAS_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones
    {
        public int Id_Sesion { get; set; }
        public int Id_Usuario { get; set; }
        public System.DateTime Fecha_Hora_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Hora_Final { get; set; }
        public string Direccion_IP { get; set; }
        public string Tipo_Dispositivo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
